plugins { id 'com.android.application' }

android {
    signingConfigs {
        debug {
            storeFile file("${System.getProperty('user.home')}/.android/debug.keystore")
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }
    namespace 'com.terrain.commander'; compileSdk 35
    defaultConfig { testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'; applicationId 'com.terrain.commander'; minSdk 26; targetSdk 35; versionCode 9; versionName '2.7' }
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test:runner:1.6.2'
    androidTestImplementation 'junit:junit:4.13.2'
}
